### ISSUE TITLE
rnd.partition(1, 0, 0) fails

### ISSUE THREAD

**Issue by dario2994** [MikeMirzayanov/testlib#129] opened 2021-06-26 14:18 UTC
When calling `rnd.partition(1, 0, 0)` the error `FAIL random_t::distinct expected from <= to` is raised, even though the parameters seem correct.

**Comment by shishyando** [comment] 2021-07-25 11:58
In the current version of testlib.h (0.9.37-SNAPSHOT) rnd.partition() and rnd.distinct() work fine, the problem is that on polygon the version is 0.9.34-SNAPSHOT

The polygon version of testlib.h should be updated to fix the issue

**Comment by MikeMirzayanov** [comment] 2022-07-26 09:28
Fixed now, will be in Ploygon soon

**Closed by MikeMirzayanov** 2022-07-26 09:28 UTC
